### GET ALL USERS
GET https://be-rest-872136705893.us-central1.run.app/users

### GET USER BY ID
GET http://localhost:5000/users/1

### POST USER
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "gender": "Male"
}

### EDIT USER
PUT https://be-rest-872136705893.us-central1.run.app/users/916
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
    "gender": "Male"
}

### DELETE USER
DELETE https://be-rest-872136705893.us-central1.run.app/users/916